const CONST = {
    FLOOR_CONTAINER_ID: '#floorContainer',
    ELEVATOR_CONTAINER_ID: '#elevatorContainer',
    INIT_TOTAL_FLOOR: 5,
    INIT_TOTAL_ELEVATOR: 4,
    MAX_FLOOR: 5,
    MAX_ELEVATOR: 4,
    MIN_FLOOR: 2,
    MIN_ELEVATOR: 2,
    ELEVATOR_WIDTH: 3,
    DEFAULT_ELEVATOR_ID: 0,
    ELEVATOR_MARGIN_HORIZONTAL: 2,
    ELEVATOR_MOVE_DISTANCE: 3.37,
    ELEVATOR_START_FLOOR: 0,
    ELEVATOR_ONE_FLOOR_SPEED: 1000,
    ELEVATOR_OPEN_TIME: 3000,
    EVENT: {
        MODEL_UPDATE: {
            CALL_ELEVATOR: 'CALL_ELEVATOR',
            MOVE_ELEVATOR: 'MOVE_ELEVATOR',
            ACTIVATING_FLOOR: 'ACTIVATING_FLOOR',
            MISSING_TARGET_ELEVATOR: 'MISSING_TARGET_ELEVATOR',
        }
    },
    API_CODE: {
        SUCCESS: 1,
        FAIL: 0
    },
    API_ERROR_CODE: {
        NOT_FOUND_FLOOR_OR_ELEVATOR: 1
    }
};

export default CONST;